
ARG JMETER_VERSION
FROM rbillon59/jmeter-k8s-base:${JMETER_VERSION}

# Taurus JMeter plugin installation
RUN ./PluginsManagerCMD.sh install jpgc-casutg,jpgc-dummy,jpgc-ffw,jpgc-fifo,jpgc-functions,jpgc-json,jpgc-perfmon,jpgc-prmctl,jpgc-tst


ARG PROJECT
ENV ENV_PROJECT=${PROJECT}

COPY scenario /tmp/scenario
COPY entrypoint.sh /tmp/entrypoint.sh

USER jmeter
WORKDIR /opt/jmeter/apache-jmeter/bin

ENTRYPOINT "/tmp/entrypoint.sh" ${ENV_PROJECT}

